### ISSUE TITLE
var textareaElement; is global plugin wise thus preventing multiple instances of the plugin

### ISSUE THREAD

**Issue by LukasLt** [rallu/angular-lightweight-markdown-editor#9]
I was trying to setup multiple editors in single page and it was failing.

The problem is at `var textareaElement` being declared at plugin loading scope. 
This leads to a situation where `textareaElement` will always going to reference the latest instance of editor. 

We should find a solution to refactor linking function to use  `textareaElement` per instance.

Should I create pull request for this?

**Comment by rallu** [comment]
Go a head. I'm happy to merge if you create working solution.

**Comment by LukasLt** [comment]
Thanks for quick response!

Will this be published to  https://www.npmjs.com/package/angular-lightweight-markdown-editor ?

**Comment by rallu** [comment]
Looks like someone else has registered it to npm. I haven't done it.

**Comment by rallu** [comment]
I requested from the person who registered that I would be added to as admin. Let's see if it happens. If nothing happens in 4 weeks I'll contact NPM.
